server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authDB?serverTimezone=EST5EDT&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update  
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: update
logging:
  level:
    org:
      hibernate:
        type: trace
